name: 'Structural Workspace Export'
description: 'Export configuration from your Tonic Structural workspace'
author: 'Tonic.ai'
branding:
  icon: "upload"
  color: "blue"
inputs:
  api_key:
    description: 'Structural API key with access to the workspace'
    required: true
  workspace_id:
    description: 'ID of the Tonic workspace to export'
    required: true
  base-url:
    description: 'Base URL for Tonic API'
    required: false
    default: 'https://app.tonic.ai'
  output_path:
    description: 'Path where the export file will be saved'
    required: false
    default: 'workspace-export.json'

outputs:
  export_path:
    description: 'Path to the exported workspace configuration file'
    value: ${{ steps.export.outputs.export_path }}

runs:
  using: 'composite'
  steps:
    - name: Export workspace configuration
      id: export
      shell: bash
      run: |
        # Create output directory if it doesn't exist
        mkdir -p "$(dirname "${{ inputs.output_path }}")"

        # Run curl to export workspace configuration
        curl --fail --silent --show-error \
          -X GET "${{ inputs.base-url }}/api/workspace/${{ inputs.workspace_id }}/export" \
          -H "Authorization: APIKEY ${{ inputs.api_key }}" \
          -H "Content-Type: application/json" \
          -o "${{ inputs.output_path }}"

        # Check if export was successful
        if [ $? -eq 0 ]; then
          echo "Workspace configuration successfully exported to ${{ inputs.output_path }}"
          echo "export_path=${{ inputs.output_path }}" >> $GITHUB_OUTPUT
        else
          echo "Failed to export workspace configuration"
          exit 1
        fi